### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Hakuna-23** [lasselukkari/DuinoDCX#135] opened 2019-10-13 17:22 UTC
Hello first of all thank you for this great shit :)
i hope you can help me with my problem .
I do everything like in the guide and all works well during the point i want to start the remote control after entering the username and password it is only searching the howl time and i can not to anything. Do you have an idea what is maby wrong?

thank you very much

![grafik](https://user-images.githubusercontent.com/56515626/66719321-802ddf00-edee-11e9-811d-9d156ddd9876.png)

**Comment by killerops** [comment] 2019-10-13 20:31
I also have this issue on iOS, but on chrome in Android works well.
Tested on Chrome on iPhone7 and iPad2.

**Comment by Hakuna-23** [comment] 2019-10-14 04:05
OK I tried it on chrome on Android but the same problem :(

**Comment by lasselukkari** [comment] 2019-10-14 07:02
Hi. There is an indication of two possible problems in your screenshot. 

1. The `Searching...` text shows up when the the DuinoDCX controller is not able to communicate with the Ultradrive using the RSR232 port. This is most likely caused by bad wiring or problems with the Ultradrive `PORT` settings.
2. The `Check network connection` message pops up when the browser is not able to make requests to controller. Is this message constantly there or did it popup after you disconnected from the wifi network create by the DuinoDCX?

I will try to prepare a better step by step troubleshooting guide this week. In the meantime it would be really nice if you could update the bug report to use this [template](https://raw.githubusercontent.com/lasselukkari/DuinoDCX/master/.github/ISSUE_TEMPLATE/bug_report.md).

Previously the Arduino ESP32 core has had problems with some operating systems, mostly with Windows. These should have been now finally fixed since the core version 1.0.3.

**Comment by lasselukkari** [comment] 2019-10-14 16:27
I just realized the hardware test sketch may have given false positives in some situations. Could you both verify again with the updated [HardwareTest](https://github.com/lasselukkari/DuinoDCX/blob/master/HardwareTest/HardwareTest.ino) that your hardware configuration is working as expected. The instructions are included in the comments.

**Comment by lasselukkari** [comment] 2019-10-14 19:37
I also today tested the app on different configurations and found a bug in the webserver header handling. This is now fixed in the latest release.

I tested the setup successfully with latest versions of:
* Mac + Chrome
* Mac + Firefox
* Mac + Safari
* Android + Chrome
* Ubuntu + Chrome
* Ubuntu + Firefox
* Windows 7 + Chrome
* Windows 7 + Edge

**Comment by lasselukkari** [comment] 2019-11-14 21:27
I'm closing this due to inactivity for one month. Feel free to reopen the issue if needed.

**Closed by lasselukkari** 2019-11-14 21:27 UTC
